list:
    @just -l

theme-gruvbox-dark:
    cd template_renderer && cat ../themes/gruvbox.toml | poetry run python renderer.py variant=dark ../themes/gruvbox.jinja2 > ../../hedgehog-tui/data/gruvbox-dark.theme

theme-gruvbox-light:
    cd template_renderer && cat ../themes/gruvbox.toml | poetry run python renderer.py variant=light ../themes/gruvbox.jinja2 > ../../hedgehog-tui/data/gruvbox-light.theme

theme-gruvbox: theme-gruvbox-dark theme-gruvbox-light
