list:
    @just -l

theme-gruvbox variant:
    cd template_renderer && cat ../themes/gruvbox.toml | poetry run python renderer.py variant={{variant}} ../themes/gruvbox.jinja2 > ../../hedgehog-tui/data/gruvbox-{{variant}}.theme

theme-gruvbox-all:
    just theme-gruvbox dark
    just theme-gruvbox light

theme-solarized variant:
    cd template_renderer && cat ../themes/solarized.toml | poetry run python renderer.py variant={{variant}} ../themes/solarized.jinja2 > ../../hedgehog-tui/data/solarized-{{variant}}.theme

theme-solarized-all:
    just theme-solarized dark
    just theme-solarized light

theme-nord:
    cd template_renderer && cat ../themes/nord.toml | poetry run python renderer.py variant=dark ../themes/nord.jinja2 > ../../hedgehog-tui/data/nord.theme

theme: theme-solarized-all theme-gruvbox-all theme-nord
