list:
    jest -l

theme-gruvbox-dark:
    handlebars-cli "$(cat ./theme-templates/gruvbox-dark.json)" ./theme-templates/gruvbox.tera > ../data/gruvbox-dark.theme

theme-gruvbox-light:
    handlebars-cli "$(cat ./theme-templates/gruvbox-light.json)" ./theme-templates/gruvbox.tera > ../data/gruvbox-light.theme

theme-gruvbox: theme-gruvbox-dark theme-gruvbox-light
