set statusbar.status.error fg:red
set statusbar.status.warning fg:yellow
set statusbar.status.information fg:blue
set statusbar.command.prompt fg:cyan
set statusbar.confirmation fg:yellow

set list.item:selected +reversed

set player.title bg:darkgray
set player.status.none bg:black
set player.status.playing bg:green fg:black
set player.status.paused bg:blue fg:black
set player.status.buffering bg:red fg:black
set player.timing bg:blue fg:black

set empty.title +bold
