on:
  pull_request:
  push:
    branches:
      - trunk

jobs:
  test-linux:
    name: test-linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install cargo and tools
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libsqlite3-dev libdbus-1-3 libssl-dev libgstreamer1.0-dev 

      - name: Run tests
        run: cargo test --all

      - name: Run fmt
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --all -- -D  warnings -D clippy::semicolon-if-nothing-returned

  test-windows:
    name: test-windows
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install cargo and tools
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies
        shell: pwsh
        run: |
          choco install --yes gstreamer gstreamer-devel
          choco install --yes pkgconfiglite --download-checksum 2038c49d23b5ca19e2218ca89f06df18fe6d870b4c6b54c0498548ef88771f6f --download-checksum-type sha256 --version 0.28
          "C:\\gstreamer\\1.0\\msvc_x86_64\\bin" >> $env:GITHUB_PATH

      - name: Run tests
        run: cargo test --all
        env:
          PKG_CONFIG_PATH: C:\gstreamer\1.0\msvc_x86_64\lib\pkgconfig


